repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["-a", "from __future__ import annotations"]

- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    args: ["--py37-plus", "--keep-runtime-typing"]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    exclude: docs/conf.py
    additional_dependencies: [flake8-bugbear, flake8-print]

- repo: https://github.com/hadialqattan/pycln
  rev: "v1.2.5"
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
    stages: [manual]


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.940
  hooks:
  - id: mypy
    files: src
    args: [--show-error-codes]
    additional_dependencies: [rich, click, hist, numpy, textual==0.1.17]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: [-L, "hist,iterm"]

- repo: local
  hooks:
  - id: disallow-caps
    name: Disallow improper capitalization
    language: pygrep
    entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
    exclude: .pre-commit-config.yaml
