[build-system]
requires = ["flit_core >=3.3"]
build-backend = "flit_core.buildapi"

[project]
name = "uproot_browser"
authors = [
  { name = "Henry Schreiner", email = "henryfs@princeton.edu" },
]
maintainers = [
  { name = "The Scikit-HEP admins", email = "scikit-hep-admins@googlegroups.com" },
]
license = { file = "LICENSE" }

description = "Tools to inspect ROOT files with uproot"
readme = "README.md"

requires-python = ">=3.7"

classifiers = [
  "License :: OSI Approved :: BSD License",
  "Topic :: Scientific/Engineering",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Development Status :: 2 - Pre-Alpha",
  "Typing :: Typed",
]


dynamic = ["version"]
dependencies = [
  "awkward >=1",
  "click >=7",
  "lz4",
  "numpy >=1.13.3",
  "rich >=10.0.0",
  "uproot >=4.0",
  "xxhash",
  "plotext >=4.1.0",
]

# Maybe later:
# "hist >=2.4",
# "textual >?=?",

[project.optional-dependencies]
test = [
  "pytest >=6",
]
dev = [
  "flit >=3.3",
  "ipython >=6",
  "pytest >=6",
]
docs = [
  "Sphinx~=3.0",
  "myst_parser>=0.13",
  "sphinx-book-theme>=0.1.0",
  "sphinx_copybutton",
]

[project.urls]
homepage = "https://github.com/henryiii/uproot-browser"
repository = "https://github.com/henryiii/uproot-browser"

[project.scripts]
uproot-browser = "uproot_browser.__main__:main"


[tool.pytest.ini_options]
addopts = ["-ra"]
testpaths = ["tests"]


[tool.isort]
profile = "black"


[tool.mypy]
files = "src"
python_version = "3.7"
warn_unused_configs = true
strict = true

[[tool.mypy.overrides]]
module = ["plotext.*", "awkward.*", "uproot.*"]
ignore_missing_imports = true
